# Generated by Django 5.0.2 on 2024-02-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolls', models.CharField(choices=[('Django Admin', 'Django Admin'), ('Common', 'Common'), ('Anonymous', 'Anonymous'), ('IFC JC Admin', 'IFC JC Admin'), ('IFC JC Counselor', 'IFC JC Counselor')], default='Common', max_length=20)),
            ],
        ),
    ]
