# Generated by Django 5.0.2 on 2024-02-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_rolls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rolls',
            field=models.CharField(choices=[('IFC JC Admin', 'IFC JC Admin'), ('Common', 'Common'), ('Anonymous', 'Anonymous'), ('IFC JC Counselor', 'IFC JC Counselor'), ('Django Admin', 'Django Admin')], default='Common', max_length=20),
        ),
    ]
