# Generated by Django 5.0.2 on 2024-02-29 00:39

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_rolls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_reporter', models.CharField(blank=True, max_length=100, null=True)),
                ('email_of_reporter', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_num_of_reporter', models.IntegerField(blank=True, null=True)),
                ('date_of_incident', models.DateField()),
                ('time_of_incident', models.TimeField()),
                ('organization_of_reporter', models.CharField(blank=True, max_length=100, null=True)),
                ('location_of_incident', models.CharField(blank=True, max_length=150, null=True)),
                ('description_of_event', models.TextField()),
                ('violated_standards_conduct', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(14)]), size=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='rolls',
            field=models.CharField(choices=[('Common', 'Common'), ('Anonymous', 'Anonymous'), ('IFC JC Admin', 'IFC JC Admin'), ('IFC JC Counselor', 'IFC JC Counselor'), ('Django Admin', 'Django Admin')], default='Common', max_length=20),
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(max_length=1024)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='users.report')),
            ],
        ),
    ]
