# Generated by Django 5.0.2 on 2024-02-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_report_alter_user_rolls_reportfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rolls',
            field=models.CharField(choices=[('IFC JC Admin', 'IFC JC Admin'), ('Common', 'Common'), ('Django Admin', 'Django Admin'), ('IFC JC Counselor', 'IFC JC Counselor'), ('Anonymous', 'Anonymous')], default='Common', max_length=20),
        ),
    ]
