# Generated by Django 5.0.2 on 2024-02-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_rolls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rolls',
            field=models.CharField(choices=[('IFC JC Counselor', 'IFC JC Counselor'), ('Django Admin', 'Django Admin'), ('IFC JC Admin', 'IFC JC Admin'), ('Anonymous', 'Anonymous'), ('Common', 'Common')], default='Common', max_length=20),
        ),
    ]
