# Generated by Django 5.0.2 on 2024-03-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_rolls'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='name_of_accused_fraternity',
            field=models.CharField(default='CENTENNIAL', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='rolls',
            field=models.CharField(choices=[('IFC JC Admin', 'IFC JC Admin'), ('IFC JC Counselor', 'IFC JC Counselor'), ('Django Admin', 'Django Admin'), ('Anonymous', 'Anonymous'), ('Common', 'Common')], default='Common', max_length=20),
        ),
    ]
