# Generated by Django 5.0.2 on 2024-03-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_report_name_of_accused_fraternity_alter_user_rolls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='name_of_accused_fraternity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='rolls',
            field=models.CharField(choices=[('Anonymous', 'Anonymous'), ('IFC JC Counselor', 'IFC JC Counselor'), ('IFC JC Admin', 'IFC JC Admin'), ('Common', 'Common'), ('Django Admin', 'Django Admin')], default='Common', max_length=20),
        ),
    ]
