# Generated by Django 5.0.2 on 2024-03-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_report_name_of_accused_fraternity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='phone_num_of_reporter',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rolls',
            field=models.CharField(choices=[('IFC JC Counselor', 'IFC JC Counselor'), ('Anonymous', 'Anonymous'), ('IFC JC Admin', 'IFC JC Admin'), ('Django Admin', 'Django Admin'), ('Common', 'Common')], default='Common', max_length=20),
        ),
    ]
