# Generated by Django 5.0.2 on 2024-03-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_report_phone_num_of_reporter_alter_user_rolls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportfile',
            name='file_url',
        ),
        migrations.AddField(
            model_name='reportfile',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rolls',
            field=models.CharField(choices=[('Django Admin', 'Django Admin'), ('Common', 'Common'), ('Anonymous', 'Anonymous'), ('IFC JC Admin', 'IFC JC Admin'), ('IFC JC Counselor', 'IFC JC Counselor')], default='Common', max_length=20),
        ),
    ]
