# Generated by Django 4.2.10 on 2024-03-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_report_phone_num_of_reporter_alter_user_rolls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rolls',
            field=models.CharField(choices=[('Common', 'Common'), ('IFC JC Admin', 'IFC JC Admin'), ('IFC JC Counselor', 'IFC JC Counselor'), ('Anonymous', 'Anonymous'), ('Django Admin', 'Django Admin')], default='Common', max_length=20),
        ),
    ]
