# Generated by Django 5.0.2 on 2024-03-16 04:27

import storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_reportfile_file_url_reportfile_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='file',
            field=models.FileField(blank=True, null=True, storage=storage_backends.MediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='rolls',
            field=models.CharField(choices=[('Django Admin', 'Django Admin'), ('Common', 'Common'), ('Anonymous', 'Anonymous'), ('IFC JC Counselor', 'IFC JC Counselor'), ('IFC JC Admin', 'IFC JC Admin')], default='Common', max_length=20),
        ),
    ]
