# Generated by Django 5.0.2 on 2024-03-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_standardofconduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rolls',
            field=models.CharField(choices=[('IFC JC Admin', 'IFC JC Admin'), ('IFC JC Counselor', 'IFC JC Counselor'), ('Anonymous', 'Anonymous'), ('Common', 'Common'), ('Django Admin', 'Django Admin')], default='Common', max_length=20),
        ),
    ]
