# Generated by Django 5.0.2 on 2024-03-15 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_rolls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardofconduct',
            name='standard',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='rolls',
            field=models.CharField(choices=[('IFC JC Admin', 'IFC JC Admin'), ('Anonymous', 'Anonymous'), ('Django Admin', 'Django Admin'), ('Common', 'Common'), ('IFC JC Counselor', 'IFC JC Counselor')], default='Common', max_length=20),
        ),
    ]
