# Generated by Django 5.0.2 on 2024-03-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20240315_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rolls',
            field=models.CharField(choices=[('IFC JC Counselor', 'IFC JC Counselor'), ('Common', 'Common'), ('Django Admin', 'Django Admin'), ('Anonymous', 'Anonymous'), ('IFC JC Admin', 'IFC JC Admin')], default='Common', max_length=20),
        ),
    ]
