# Generated by Django 4.2.11 on 2024-03-17 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_reportfile_file_alter_user_rolls'),
        ('users', '0020_alter_report_email_of_reporter_and_more'),
    ]

    operations = [
    ]
