# Generated by Django 4.2.10 on 2024-03-18 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_rolls'),
        ('users', '0025_alter_user_rolls'),
    ]

    operations = [
    ]
