# Generated by Django 4.2.10 on 2024-03-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_merge_0014_alter_user_rolls_0025_alter_user_rolls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rolls',
            field=models.CharField(choices=[('Anonymous', 'Anonymous'), ('IFC JC Counselor', 'IFC JC Counselor'), ('Common', 'Common'), ('IFC JC Admin', 'IFC JC Admin'), ('Django Admin', 'Django Admin')], default='Common', max_length=20),
        ),
    ]
