# Generated by Django 5.0.2 on 2024-03-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_user_rolls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rolls',
            field=models.CharField(choices=[('Common', 'Common'), ('Anonymous', 'Anonymous'), ('IFC JC Counselor', 'IFC JC Counselor'), ('Django Admin', 'Django Admin'), ('IFC JC Admin', 'IFC JC Admin')], default='Common', max_length=20),
        ),
    ]
