# Generated by Django 5.0.2 on 2024-03-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_user_rolls'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in progress', 'In Progress'), ('resolved', 'Resolved')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='rolls',
            field=models.CharField(choices=[('Anonymous', 'Anonymous'), ('Common', 'Common'), ('IFC JC Counselor', 'IFC JC Counselor'), ('IFC JC Admin', 'IFC JC Admin'), ('Django Admin', 'Django Admin')], default='Common', max_length=20),
        ),
    ]
