# Generated by Django 5.0.2 on 2024-03-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_report_status_alter_user_rolls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in progress', 'In Progress'), ('resolved', 'Resolved')], default='new', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rolls',
            field=models.CharField(choices=[('IFC JC Counselor', 'IFC JC Counselor'), ('Django Admin', 'Django Admin'), ('Common', 'Common'), ('Anonymous', 'Anonymous'), ('IFC JC Admin', 'IFC JC Admin')], default='Common', max_length=20),
        ),
    ]
