# Generated by Django 5.0.2 on 2024-03-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_user_rolls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rolls',
            field=models.CharField(choices=[('Django Admin', 'Django Admin'), ('Common', 'Common'), ('Anonymous', 'Anonymous'), ('IFC JC Admin', 'IFC JC Admin'), ('IFC JC Counselor', 'IFC JC Counselor')], default='Common', max_length=20),
        ),
    ]
