# Generated by Django 5.0.2 on 2024-03-26 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_report_status_alter_user_rolls'),
        ('users', '0031_alter_user_rolls'),
    ]

    operations = [
    ]
