# Generated by Django 5.0.2 on 2024-03-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_merge_20240326_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rolls',
            field=models.CharField(choices=[('Anonymous', 'Anonymous'), ('Common', 'Common'), ('IFC JC Counselor', 'IFC JC Counselor'), ('IFC JC Admin', 'IFC JC Admin'), ('Django Admin', 'Django Admin')], default='Common', max_length=20),
        ),
    ]
