# Generated by Django 5.0.2 on 2024-03-28 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_merge_20240326_1237'),
        ('users', '0032_merge_20240326_1253'),
    ]

    operations = [
    ]
