# Generated by Django 5.0.2 on 2024-03-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_user_rolls'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reviewer_comments',
            field=models.TextField(blank=True, default='No review yet', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rolls',
            field=models.CharField(choices=[('Common', 'Common'), ('Anonymous', 'Anonymous'), ('IFC JC Counselor', 'IFC JC Counselor'), ('Django Admin', 'Django Admin'), ('IFC JC Admin', 'IFC JC Admin')], default='Common', max_length=20),
        ),
    ]
