# Generated by Django 5.0.2 on 2024-04-01 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_merge_20240328_1645'),
        ('users', '0036_alter_user_rolls'),
    ]

    operations = [
    ]
