# Generated by Django 5.0.3 on 2024-04-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_merge_0033_merge_20240328_1645_0036_alter_user_rolls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rolls',
            field=models.CharField(choices=[('Anonymous', 'Anonymous'), ('Django Admin', 'Django Admin'), ('IFC JC Counselor', 'IFC JC Counselor'), ('Common', 'Common'), ('IFC JC Admin', 'IFC JC Admin')], default='Common', max_length=20),
        ),
    ]
