# Generated by Django 5.0.2 on 2024-04-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_user_rolls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rolls',
            field=models.CharField(choices=[('Anonymous', 'Anonymous'), ('IFC JC Admin', 'IFC JC Admin'), ('Django Admin', 'Django Admin'), ('IFC JC Counselor', 'IFC JC Counselor'), ('Common', 'Common')], default='Common', max_length=20),
        ),
    ]
